#!/bin/bash

build_type="$1"

function find_compile_command_dbs() {
  for i in * ; do
    build_dir="$i/build/$build_type"
    if [ -d "$build_dir" ] && [ -f "$build_dir/compile_commands.json" ]; then
      echo "$build_dir/compile_commands.json"
    fi
  done
}

jq '.[]' $(find_compile_command_dbs) | jq -s '.' > compile_commands.json
